name: (kuberlr-kubectl) Image Release

on:
  push:
    tags:
      - 'v*'

env:
  IMAGE_REPO: "mallardduck/rancher-kuberlr"

# GitHub settings / example values:
#
# org level vars:
#   - PUBLIC_REGISTRY: docker.io
# repo level vars:
#   - PUBLIC_REGISTRY_REPO: rancher
# repo level secrets:
#   - PUBLIC_REGISTRY_USERNAME
#   - PUBLIC_REGISTRY_PASSWORD

permissions:
  contents: write # Upload artefacts to release.

jobs:

  publish-public:
    runs-on: ubuntu-latest

    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@e92390c5fb421da1463c202d546fed0ec5c39f20 # v3.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb # v3.3.0
      - name: Check out repository code
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5

      - name: Build and push all image variations
        run: |
          make image-push
          TAG="${TAG}-amd64" TARGET_PLATFORMS=linux/amd64 make image-push
          TAG="${TAG}-arm64" TARGET_PLATFORMS=linux/arm64 make image-push
          TAG="${TAG}-s390x" TARGET_PLATFORMS=linux/s390x make image-push
        env:
          TAG: ${{ github.ref_name }}
          REPO: ${{ env.IMAGE_REPO }}