name: (kuberlr-base) Validate PR
on:
  workflow_call:
  pull_request:
    paths:
      - 'base/**'
  pull_request_review:
    types: [ submitted ]
jobs:
  validate-versions:
    name: "Check kuberlr release versions"
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
      - run: scripts/check-kuberlr-versions.sh base/versions.txt